from __future__ import annotations

import re
from typing import Any


DEFAULT_COLUMN = {
    "name": "id",
    "type": "INT",
    "primaryKey": True,
    "autoIncrement": True,
    "nullable": False,
}


def _quote_identifier(name: str) -> str:
    safe_name = (name or "").strip().replace("`", "")
    if not safe_name:
        raise ValueError("Identifier names cannot be empty")
    return f"`{safe_name}`"


def _constraint_action(value: Any, default: str) -> str:
    action = str(value or default).upper()
    allowed = {"CASCADE", "RESTRICT", "SET NULL", "NO ACTION"}
    return action if action in allowed else default


def _column_type(value: Any) -> str:
    candidate = str(value or "VARCHAR(255)").upper().strip()
    if not re.fullmatch(r"[A-Z0-9(), ]+", candidate):
        raise ValueError(f"Invalid column type: {candidate}")
    return candidate


def _table_name_map(tables: list[dict[str, Any]]) -> dict[str, str]:
    table_map: dict[str, str] = {}
    for index, table in enumerate(tables, start=1):
        table_id = str(table.get("id") or f"table-{index}")
        table_name = str(table.get("name") or f"table_{index}")
        table_map[table_id] = table_name
    return table_map


def generate_sql_script(schema: dict[str, Any]) -> str:
    tables = schema.get("tables") or []
    if not isinstance(tables, list) or not tables:
        raise ValueError("Schema must include at least one table")

    relationships = schema.get("relationships") or []
    table_map = _table_name_map(tables)

    create_statements: list[str] = []
    for index, table in enumerate(tables, start=1):
        table_name = str(table.get("name") or f"table_{index}")
        columns = table.get("columns") or [DEFAULT_COLUMN]
        if not isinstance(columns, list) or not columns:
            columns = [DEFAULT_COLUMN]

        column_definitions: list[str] = []
        primary_keys: list[str] = []
        unique_keys: list[str] = []

        for col_index, column in enumerate(columns, start=1):
            column_name = str(column.get("name") or f"column_{col_index}")
            column_type = _column_type(column.get("type"))
            nullable = bool(column.get("nullable", True))
            auto_increment = bool(column.get("autoIncrement", False))
            primary_key = bool(column.get("primaryKey", False))
            unique = bool(column.get("unique", False))

            definition = f"  {_quote_identifier(column_name)} {column_type}"
            if auto_increment:
                definition += " AUTO_INCREMENT"
            if not nullable or primary_key:
                definition += " NOT NULL"
            column_definitions.append(definition)

            if primary_key:
                primary_keys.append(_quote_identifier(column_name))
            if unique and not primary_key:
                unique_keys.append(_quote_identifier(column_name))

        if primary_keys:
            column_definitions.append(f"  PRIMARY KEY ({', '.join(primary_keys)})")
        for unique_column in unique_keys:
            column_definitions.append(f"  UNIQUE ({unique_column})")

        create_statements.append(
            f"CREATE TABLE {_quote_identifier(table_name)} (\n"
            + ",\n".join(column_definitions)
            + "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
        )

    alter_statements: list[str] = []
    for rel_index, relation in enumerate(relationships, start=1):
        from_table_name = table_map.get(str(relation.get("fromTableId") or ""))
        to_table_name = table_map.get(str(relation.get("toTableId") or ""))
        from_column = relation.get("fromColumn")
        to_column = relation.get("toColumn")

        if not (from_table_name and to_table_name and from_column and to_column):
            continue

        delete_action = _constraint_action(relation.get("onDelete"), "RESTRICT")
        update_action = _constraint_action(relation.get("onUpdate"), "CASCADE")
        constraint_name = f"fk_{rel_index}_{from_table_name}_{to_table_name}".replace(" ", "_")

        alter_statements.append(
            f"ALTER TABLE {_quote_identifier(from_table_name)} "
            f"ADD CONSTRAINT {_quote_identifier(constraint_name)} "
            f"FOREIGN KEY ({_quote_identifier(str(from_column))}) "
            f"REFERENCES {_quote_identifier(to_table_name)} ({_quote_identifier(str(to_column))}) "
            f"ON DELETE {delete_action} ON UPDATE {update_action};"
        )

    sections = [
        "-- Generated by ERD Studio",
        "SET NAMES utf8mb4;",
        *create_statements,
        *alter_statements,
    ]
    return "\n\n".join(sections) + "\n"
