const DEFAULT_COLUMN = {
  name: 'id',
  type: 'INT',
  primaryKey: true,
  autoIncrement: true,
  nullable: false,
}

function quoteIdentifier(name) {
  const safeName = String(name || '')
    .trim()
    .replaceAll('`', '')
  if (!safeName) {
    throw new Error('Identifier names cannot be empty')
  }
  return `\`${safeName}\``
}

function constraintAction(value, defaultValue) {
  const action = String(value || defaultValue).toUpperCase()
  const allowed = new Set(['CASCADE', 'RESTRICT', 'SET NULL', 'NO ACTION'])
  return allowed.has(action) ? action : defaultValue
}

function columnType(value) {
  const candidate = String(value || 'VARCHAR(255)')
    .toUpperCase()
    .trim()
  if (!/^[A-Z0-9(), ]+$/.test(candidate)) {
    throw new Error(`Invalid column type: ${candidate}`)
  }
  return candidate
}

function tableNameMap(tables) {
  const tableMap = {}
  for (const [index, table] of tables.entries()) {
    const tableId = String(table?.id || `table-${index + 1}`)
    const tableName = String(table?.name || `table_${index + 1}`)
    tableMap[tableId] = tableName
  }
  return tableMap
}

export function generateSqlScript(schema) {
  const tables = schema?.tables || []
  if (!Array.isArray(tables) || tables.length === 0) {
    throw new Error('Schema must include at least one table')
  }

  const relationships = schema?.relationships || []
  const tableMap = tableNameMap(tables)
  const createStatements = []

  for (const [tableIndex, table] of tables.entries()) {
    const tableName = String(table?.name || `table_${tableIndex + 1}`)
    let columns = table?.columns || [DEFAULT_COLUMN]
    if (!Array.isArray(columns) || columns.length === 0) {
      columns = [DEFAULT_COLUMN]
    }

    const columnDefinitions = []
    const primaryKeys = []
    const uniqueKeys = []

    for (const [columnIndex, column] of columns.entries()) {
      const columnName = String(column?.name || `column_${columnIndex + 1}`)
      const type = columnType(column?.type)
      const nullable = Boolean(column?.nullable ?? true)
      const autoIncrement = Boolean(column?.autoIncrement ?? false)
      const primaryKey = Boolean(column?.primaryKey ?? false)
      const unique = Boolean(column?.unique ?? false)

      let definition = `  ${quoteIdentifier(columnName)} ${type}`
      if (autoIncrement) {
        definition += ' AUTO_INCREMENT'
      }
      if (!nullable || primaryKey) {
        definition += ' NOT NULL'
      }
      columnDefinitions.push(definition)

      if (primaryKey) {
        primaryKeys.push(quoteIdentifier(columnName))
      }
      if (unique && !primaryKey) {
        uniqueKeys.push(quoteIdentifier(columnName))
      }
    }

    if (primaryKeys.length > 0) {
      columnDefinitions.push(`  PRIMARY KEY (${primaryKeys.join(', ')})`)
    }
    for (const uniqueColumn of uniqueKeys) {
      columnDefinitions.push(`  UNIQUE (${uniqueColumn})`)
    }

    createStatements.push(
      `CREATE TABLE ${quoteIdentifier(tableName)} (\n${columnDefinitions.join(',\n')}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
    )
  }

  const alterStatements = []
  for (const [relationIndex, relation] of relationships.entries()) {
    const fromTableName = tableMap[String(relation?.fromTableId || '')]
    const toTableName = tableMap[String(relation?.toTableId || '')]
    const fromColumn = relation?.fromColumn
    const toColumn = relation?.toColumn

    if (!(fromTableName && toTableName && fromColumn && toColumn)) {
      continue
    }

    const deleteAction = constraintAction(relation?.onDelete, 'RESTRICT')
    const updateAction = constraintAction(relation?.onUpdate, 'CASCADE')
    const constraintName = `fk_${relationIndex + 1}_${fromTableName}_${toTableName}`.replaceAll(' ', '_')

    alterStatements.push(
      `ALTER TABLE ${quoteIdentifier(fromTableName)} ADD CONSTRAINT ${quoteIdentifier(constraintName)} FOREIGN KEY (${quoteIdentifier(String(fromColumn))}) REFERENCES ${quoteIdentifier(toTableName)} (${quoteIdentifier(String(toColumn))}) ON DELETE ${deleteAction} ON UPDATE ${updateAction};`,
    )
  }

  return ['-- Generated by ERD Studio', 'SET NAMES utf8mb4;', ...createStatements, ...alterStatements].join('\n\n') + '\n'
}
